#!/bin/bash
Magnet=$(zenity \
--entry --title "Peerflix" \
--text="Paste the magnet link for the video you want to watch:" \
--ok-label "Watch in VLC");

TorrentTitle=$(echo "$Magnet" | \
	awk -F '&dn=' '{ print $2 }' | \
	sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | \
	xargs echo -e| \
	tr "+" " "| \
	awk -F'&' '{print $1}')


peerflix "$Magnet" --vlc | \
zenity --progress --pulsate \
--title="Peerflix" \
--auto-kill --auto-close \
--text="Downloading/sending ... \n<b>$TorrentTitle</b>" \
--cancel-label "Quit"

